import { type Metadata } from "next";
import AuthWrapper from "../../components/AuthWrapper";
import RoleWrapper from "../../components/RoleWrapper";

export const metadata: Metadata = {
  title: "Kora",
  description: "Generated by Next gen",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <section className="w-full">
      <RoleWrapper >{children}</RoleWrapper>
    </section>
  );
}
